### ISSUE TITLE
False detection of ligatures in strings

### ISSUE THREAD

**Issue by sedwards2009** [princjef/font-ligatures#17]
FiraCode has ligatures for `==` and `===`, and `font-ligatures` detects them correctly.

For the string `====` (4 equals signs) the Chrome web browser renders these as separate equals signs, not as a mix of ligatures. This appears to be correct and desirable behaviour.

But the `findLigatureRanges()` method reports a ligature range from [0,4]. This is incorrect. `findLigatureRanges()` should not detect or report any ligatures in the string `====`.

In terms of unittests, add the following to the list of cases in array `firaCases` in `index.spec.ts`:

  fira('====', [1146, 1146, 1146, 1146], []),

It is also interesting to note that `findLigatures()` does report the correct list of output glyphs, which probably explains why this bug hasn't been noticed before. It's `contextRanges` list is incorrect though.

**Comment by princjef** [comment]
This is actually expected behavior of the library. Ligatures are effectively defined as decision trees when processing sequences of glyphs, where the outputs are the replacements for those sequences. To avoid `====` being rendered as `===` `=`, the font actually has to define that if a sequence of three equals signs is followed by another equals sign, it should generate a replacement of four separate equals signs.

This is why you're seeing that despite a "ligature" having been identified in that sequence of characters, it still produces the right set of glyphs and is rendered properly. This is consistent with how the font's replacements are expected to be processed.

**Comment by sedwards2009** [comment]
Thanks for the explanation. It is a bit counter intuitive when a rule has to "undo" the work of a previous rule.
